Task23_Low/Controllers/GuestController.cs
using AutoMapper;
using BLL;
using BLL.Interfaces;
using BLL.Services;
using DAL1.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Task23_Advanced.Models;

namespace Task23_Advanced.Controllers
{
    public class GuestController : Controller
    {
        private IReviewsService reviewsService;
        public GuestController(IReviewsService serv)
        {
            reviewsService = serv;
        }
        // GET: Guest
        public ActionResult Index(int? page)
        {
            IEnumerable<ReviewDTO> reviewsDtos = reviewsService.GetReviews();
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<ReviewDTO, ReviewViewModel>()).CreateMapper();
            var reviews = mapper.Map<IEnumerable<ReviewDTO>, List<ReviewViewModel>>(reviewsDtos);
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(reviews.ToPagedList(pageNumber, pageSize));
        }
    }
}

Task23_Low/Controllers/HomeController.cs
using AutoMapper;
using BLL.DTO;
using BLL.Services;
using BLL.Interfaces;
using BLL.DTO;
using DAL1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Task23_Advanced.Models;

namespace Task23_Advanced.Controllers
{
    public class HomeController : Controller
    {
        INewsService newsService;
        public HomeController(INewsService serv)
        {
            newsService = serv;
        }
        // GET: Main
        public ActionResult Index()
        {
            IEnumerable<NewsDTO> newsDtos = newsService.GetNews();
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<NewsDTO, NewsViewModel>()).CreateMapper();
            var news = mapper.Map<IEnumerable<NewsDTO>, List<NewsViewModel>>(newsDtos);
            return View(news);
        }
       
    }
}

Task23_Low/Controllers/MainController.cs
using AutoMapper;
using BLL.DTO;
using BLL.Interfaces;
using PagedList;
using DAL1.Models;
using System.Collections.Generic;
using System.Web.Mvc;
using Task23_Advanced.Models;

namespace Task23_Advanced.Controllers
{
    public class MainController : Controller
    {
        private IArticlesService articlesService;
        public MainController(IArticlesService serv)
        {
            articlesService = serv;
        }
        // GET: Main
        public ActionResult Index(int? page)
        {

            IEnumerable<ArticleDTO> articlesDtos = articlesService.GetArticles();
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<ArticleDTO, ArticleViewModel>()).CreateMapper();
            var articles = mapper.Map<IEnumerable<ArticleDTO>, List<ArticleViewModel>> (articlesDtos);
            var dividedArticles =new List<DividedArticlesViewModel>();
            foreach(var article in articles)
            {
                var lessContent = article.Content.Substring(0,199);
                var moreContent = article.Content.Substring(199);
                dividedArticles.Add(new DividedArticlesViewModel
                {
                    Date = article.Date,
                    LessContent = lessContent,
                    MoreContent = moreContent,
                    AuthorName = article.Name,
                    Id = article.Id
                }) ;
            }
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(dividedArticles.ToPagedList(pageNumber, pageSize));
        }
    }
}

Task23_Low/Controllers/QuestionnaireController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Text.RegularExpressions;
namespace Task23_Advanced.Controllers
{
    public class QuestionnaireController : Controller
    {
       
        public ActionResult Index()
        {
            ViewBag.Scales = false;
            ViewBag.Horns = false;
            ViewBag.City = false;
            ViewBag.Works = false;
            
            return View();
        }
        public JsonResult IsFullNameCorrect(string FullName)
        {
            Regex pattern =new Regex( @"[a-zA-Z'-'\s]*");
            if (pattern.IsMatch(FullName))
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            return Json(false, JsonRequestBehavior.AllowGet);
        }
       [HttpGet]
        public JsonResult IsEmailAvailable(string Email)
        {
            try
            {
                var addr = new System.Net.Mail.MailAddress(Email);
                if (addr.Address == Email)
                    return Json(true,JsonRequestBehavior.AllowGet);
                else
                    return Json(false, JsonRequestBehavior.AllowGet);
            }
            catch
            {

                return Json(false, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpPost]
        public ActionResult UserPassedData(FormCollection form)
        {

            ViewBag.TextReturn = "Your input fullname: " + form["Text"];
            ViewBag.AdressReturn = "Your input adress: " + form["Adress"];
            ViewBag.ScalesReturn = "You do not have scales";
            ViewBag.HornsReturn = "You do not have horns";
            ViewBag.RegionReturn = "Your input region: " + form["Region"];
            ViewBag.OrganisationReturn = "Your input organisation: " + form["Organisation"];
            ViewBag.EmailReturn = "Your input email: " + form["Email"];
            if (Convert.ToBoolean(form["Check-box-scales"].Split(',')[0]))
            {
                ViewBag.ScalesReturn = "You have scales";
            }
            if (Convert.ToBoolean(form["Check-box-horns"].Split(',')[0]))
            {
                ViewBag.HornsReturn = "You have horns";
            }
            ViewBag.CityReturn = "You did not checked city";
            if (form["Check-box-city"] != null && Convert.ToBoolean(form["Check-box-city"].Split(',')[0]))
            {
                ViewBag.CityReturn = "You checked city";
            }
            ViewBag.WorkReturn = "You did not checked work";
            if (form["Check-box-work"] != null && Convert.ToBoolean(form["Check-box-work"].Split(',')[0]))
            {
                ViewBag.WorkReturn = "You checked work";
            }
            ViewBag.CountryReturn = "Your input country: " + form["Country"];
            ViewBag.ExperienceReturn = "Your input experience : " + form["Experience"];
            ViewBag.PositionReturn = "Your input position: " + form["Position"];
            return View();
        }
    }
}

Task23_Low/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Task23_Low/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Task23_Low/Views/Home/Index.cshtml
@model List<Task23_Advanced.Models.NewsViewModel>
@{
    ViewBag.Title = "Library";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>
<html>
<head>
    <title>ViewBag.Title</title>
</head>
<body>
    <div class="container-lg d-flex flex-row bg-dark ">
        <div class="col-7">
            @foreach (var item in Model)
            {
                    <h2>@Html.DisplayFor(modelItem => item.Title)</h2>
                    @Html.DisplayFor(modelItem => item.Content)                  
            }
        </div>

        <div class="navbar navbar-dark bg-dark mx-auto" id="navbarSupportedContent">
            <ul class="navbar-nav flex-column justify-content-center ">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Main")">Main </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Guest")">Guest</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="@Url.Action("Index", "Questionnaire")">Questionnaire</a>
                </li>
            </ul>
        </div>
    </div>
</body>
</html>

Task23_Low/Views/Home/Main.cshtml
@{
    ViewBag.Title = "Main";
}

<h2>Main</h2>